apiVersion: v1
kind: Service
metadata:
  name: springbootecommerce
  labels:
    app: springbootecommerce
spec:
  type: LoadBalancer
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: springbootecommerce
  selector:
    app: springbootecommerce